-- ==============================================================================
-- SCRIPT DE CORREÇÃO FINAL (PERMISSÕES ESTENDIDAS)
-- ==============================================================================

-- 1. LIMPEZA (Remove tabela antiga para recriar com a estrutura limpa)
DROP TABLE IF EXISTS public.leads CASCADE;

-- 2. CRIAÇÃO DA TABELA
create table public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  property text not null,
  photos text[] default '{}'::text[] -- Array de texto para URLs
);

-- 3. PERMISSÕES DE SISTEMA (GRANT) - Nível Banco de Dados
-- Garante que o usuário anônimo possa acessar o Schema, a Tabela e Gerar IDs
GRANT USAGE ON SCHEMA public TO anon;
GRANT ALL ON TABLE public.leads TO anon;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon; -- Garante permissão no gerador de ID

-- 4. SEGURANÇA EM NÍVEL DE LINHA (RLS) - Nível de Aplicação
alter table public.leads enable row level security;

-- Política: Qualquer um (anon ou logado) pode INSERIR
create policy "Permitir inserção irrestrita"
on public.leads
for insert
to public
with check (true);

-- Política: Apenas autenticados (Admin) podem LER (Visualizar no Dashboard)
create policy "Permitir leitura para autenticados"
on public.leads
for select
to authenticated
using (true);

-- 5. CONFIGURAÇÃO DO STORAGE (BUCKET)
-- Cria o bucket 'uploads' e FORÇA ele a ser público mesmo se já existir
insert into storage.buckets (id, name, public)
values ('uploads', 'uploads', true)
on conflict (id) do update set public = true;

-- Limpa políticas antigas de storage
drop policy if exists "Upload público" on storage.objects;
drop policy if exists "Visualização pública" on storage.objects;

-- Política de Storage: Qualquer um pode fazer upload no bucket 'uploads'
create policy "Upload público"
on storage.objects
for insert
to public
with check (bucket_id = 'uploads');

-- Política de Storage: Qualquer um pode ver as imagens
create policy "Visualização pública"
on storage.objects
for select
to public
using (bucket_id = 'uploads');

-- Confirmação
SELECT 'Tabela recriada e permissões aplicadas com sucesso' as status;
